{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "multicloud-app.fullname" . }}
  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: "{{ $v }}"
    {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "multicloud-app.fullname" $. }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
{{- end }}
