apiVersion: v1
kind: Service
metadata:
  name: {{ include "multicloud-app.fullname" . | default .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}
